providers = ["php"]

[variables]
    NIXPACKS_PHP_ROOT_DIR = "/app/public"

[phases.setup]
    # We force remove the default config here. 
    # This happens during the image build, so it's gone for good.
    cmds = ["rm -f /etc/nginx/conf.d/default.conf"]

[phases.install]
    cmds = ["composer install --ignore-platform-reqs --no-interaction", "npm ci"]

[phases.build]
    cmds = ["npm run build"]

# DO NOT add a [start] section.
# Let Nixpacks use its internal, working PHP paths.
