[phases.setup]
nixPkgs = ["nodejs-22_x", "php83", "composer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader", "npm ci"]

[phases.build]
cmds = ["npm run build"]

[phases.start]
cmd = "php-fpm -D && nginx -c /app/nginx.conf"


