[phases.setup]
nixPkgs = ["nodejs-22_x", "php83", "composer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader", "npm ci"]

[phases.build]
cmds = ["npm run build"]

[phases.start]
# Force PHP built-in server, ignore Nginx
cmd = "php -S 0.0.0.0:${PORT:-3000} -t public"


