FROM ghcr.io/railwayapp/nixpacks:ubuntu-1745885067

WORKDIR /app
COPY . /app

RUN nix-env -iA nixpkgs.php83 nixpkgs.nodejs_22 nixpkgs.composer

RUN composer install --no-dev --optimize-autoloader && npm ci && npm run build

CMD ["php", "-S", "0.0.0.0:3000", "-t", "public"]
